# Changes here will be overwritten by Copier
_commit: 9642da9
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Pydantic models for supervisor
project_name: pydantic-supervisor
python_version_primary: '3.11'
team: the pydantic-supervisor authors
